name: GH Pages docker

on:
  push:
    branches: 
      - docker
  pull_request:
    branches:
      - docker
  workflow_dispatch:

jobs:
  publish-pages-docker:
    name: Deploy GH-pages docker
    runs-on: ubuntu-latest
    container: philipssoftware/node:16

    steps:
    - name: Check out code ğŸ›ï¸
      uses: actions/checkout@v2
    - name: Create confluenza pages ğŸ“¦ 
      uses: confluenza/confluenza-action@docker
      env:
        PREFIX_PATH: true
    - name: Install rsync
      run: apt-get update && apt-get install -y rsync && apt-get clean
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: public
        CLEAN: true
